# Generated by Django 2.2.4 on 2020-12-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('serviceNum', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=4, unique=True)),
                ('rank', models.CharField(choices=[('하사', '하사'), ('중사', '중사'), ('상사', '상사'), ('원사', '원사'), ('준위', '준위'), ('소위', '소위'), ('중위', '중위'), ('대위', '대위'), ('소령', '소령'), ('중령', '중령'), ('대위', '대령')], max_length=2, unique=True)),
                ('position', models.CharField(max_length=10, unique=True)),
                ('belong', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
