# Generated by Django 2.2.4 on 2020-12-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20201208_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='serviceNum',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
