# Generated by Django 2.2.4 on 2020-12-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20201208_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='belong',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='position',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='rank',
            field=models.CharField(blank=True, choices=[('하사', '하사'), ('중사', '중사'), ('상사', '상사'), ('원사', '원사'), ('준위', '준위'), ('소위', '소위'), ('중위', '중위'), ('대위', '대위'), ('소령', '소령'), ('중령', '중령'), ('대위', '대령')], max_length=2, null=True),
        ),
    ]
