# Generated by Django 2.2.4 on 2020-12-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_auto_20201211_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
