# Generated by Django 2.2.4 on 2020-12-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_auto_20201221_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_admin',
        ),
    ]
