# Generated by Django 2.2.4 on 2020-12-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_account_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='account',
            name='attemp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='blocked',
            field=models.IntegerField(default=0),
        ),
    ]
