# Generated by Django 2.2.4 on 2021-02-11 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_auto_20201228_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='blocked',
            new_name='block_no',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='attemp',
            new_name='fail_cnt',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='serviceNum',
            new_name='srvno',
        ),
        migrations.RemoveField(
            model_name='account',
            name='belong',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_waiting',
        ),
        migrations.AddField(
            model_name='account',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='regit_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 11, 9, 48, 10, 491904)),
        ),
        migrations.AddField(
            model_name='account',
            name='unit',
            field=models.CharField(choices=[('X9-1', 'X9-1대대'), ('X9-2', 'X9-2대대'), ('X9-3', 'X9-3대대'), ('X8-1', 'X8-1대대'), ('X8-2', 'X8-2대대'), ('X8-3', 'X8-3대대'), ('X7-1', 'X7-1대대'), ('X7-2', 'X7-2대대'), ('X7-3', 'X7-3대대'), ('None', 'None')], default='None', max_length=4),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='rank',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
