# Generated by Django 2.2.4 on 2021-02-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0020_auto_20210211_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='unit',
            field=models.CharField(blank=True, choices=[('X9-1', 'X9-1대대'), ('X9-2', 'X9-2대대'), ('X9-3', 'X9-3대대'), ('X8-1', 'X8-1대대'), ('X8-2', 'X8-2대대'), ('X8-3', 'X8-3대대'), ('X7-1', 'X7-1대대'), ('X7-2', 'X7-2대대'), ('X7-3', 'X7-3대대'), ('None', 'None')], max_length=4, null=True),
        ),
    ]
