# Generated by Django 2.2.4 on 2021-02-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0021_auto_20210211_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='unit',
            field=models.CharField(blank=True, choices=[('99-1', '99-1대대'), ('99-2', '99-2대대'), ('99-3', '99-3대대'), ('98-1', '98-1대대'), ('98-2', '98-2대대'), ('98-3', '98-3대대'), ('97-1', '97-1대대'), ('97-2', '97-2대대'), ('97-3', '97-3대대'), ('None', 'None')], max_length=4, null=True),
        ),
    ]
