# Generated by Django 2.2.4 on 2021-03-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0022_auto_20210222_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_level',
            field=models.IntegerField(default=1),
        ),
    ]
