# Generated by Django 2.2.4 on 2020-12-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('reserve', models.CharField(blank=True, max_length=10, null=True)),
                ('product_status', models.CharField(blank=True, choices=[('NEW', '신상품'), ('USED', '중고')], max_length=4, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model_code', models.CharField(blank=True, max_length=100, null=True)),
                ('boat_img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
