# Generated by Django 2.2.4 on 2020-12-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='reserve',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
