# Generated by Django 2.2.4 on 2020-12-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boats', '0004_auto_20201221_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteboat',
            name='wasted_img',
            field=models.ImageField(blank=True, null=True, upload_to='ship_server/Boats/img/wasted_img'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='ship_server/Boats/img/boat_img'),
        ),
    ]
