# Generated by Django 2.2.4 on 2020-12-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boats', '0005_auto_20201221_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='boat_img/'),
        ),
        migrations.AlterField(
            model_name='wasteboat',
            name='wasted_img',
            field=models.ImageField(blank=True, null=True, upload_to='wasted_img/'),
        ),
    ]
