# Generated by Django 2.2.4 on 2020-12-22 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boats', '0006_auto_20201221_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boat',
            old_name='is_learnig',
            new_name='is_learning',
        ),
    ]
