# Generated by Django 2.2.4 on 2020-12-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boats', '0007_auto_20201222_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteboat',
            name='is_learning',
            field=models.BooleanField(default=False),
        ),
    ]
