# Generated by Django 2.2.4 on 2020-12-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boats', '0008_wasteboat_is_learning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='imo',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
