# Generated by Django 2.2.4 on 2021-01-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boats', '0010_boatimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatimg',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
