# Generated by Django 2.2.4 on 2021-01-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boats', '0011_boatimg_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatimg',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='boat_img/'),
        ),
    ]
