# Generated by Django 2.2.4 on 2021-01-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boats', '0012_auto_20210121_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatimg',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='add_boat_img/'),
        ),
    ]
