# Generated by Django 2.2.4 on 2021-02-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boats', '0014_auto_20210122_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boatimg',
            name='media',
        ),
        migrations.AddField(
            model_name='boatimg',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='add_boat_img/'),
        ),
    ]
