# Generated by Django 2.2.4 on 2021-02-22 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regit_date', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('types', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(blank=True, max_length=10, null=True)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('img_cnt', models.IntegerField(default=0)),
                ('is_train', models.BooleanField(default=False)),
                ('main_img', models.ImageField(blank=True, null=True, upload_to='waste/new/%Y/%m/%d')),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WasteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regit_date', models.DateTimeField(auto_now_add=True)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('img', models.ImageField(blank=True, null=True, upload_to='waste/exist/%Y/%m/%d')),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('w_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_imgs', to='Ships.WasteShip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NormalShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regit_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('port', models.CharField(blank=True, max_length=10, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('tons', models.CharField(blank=True, max_length=10, null=True)),
                ('types', models.CharField(blank=True, max_length=10, null=True)),
                ('size', models.CharField(blank=True, max_length=15, null=True)),
                ('region', models.CharField(blank=True, max_length=10, null=True)),
                ('is_vpass', models.BooleanField(default=False)),
                ('is_ais', models.BooleanField(default=False)),
                ('is_vhf', models.BooleanField(default=False)),
                ('is_ff', models.BooleanField(default=False)),
                ('img_cnt', models.IntegerField(default=0)),
                ('is_train', models.BooleanField(default=False)),
                ('main_img', models.ImageField(blank=True, null=True, upload_to='normal/new/%Y/%m/%d')),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'NormalShip',
            },
        ),
        migrations.CreateModel(
            name='NormalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regit_date', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='normal/exist/%Y/%m/%d')),
                ('n_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normal_imgs', to='Ships.NormalShip')),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
