# Generated by Django 2.2.4 on 2021-02-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ships', '0002_auto_20210215_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalimage',
            name='media',
        ),
        migrations.RemoveField(
            model_name='wasteimage',
            name='media',
        ),
        migrations.AddField(
            model_name='normalimage',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='normal/exist/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='wasteimage',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='waste/exist/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='normalship',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='normal/new/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='wasteship',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='waste/new/%Y/%m/%d'),
        ),
    ]
