# Generated by Django 2.2.4 on 2021-02-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ships', '0003_auto_20210218_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalship',
            name='width',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='normalship',
            name='tons',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
