# Generated by Django 2.2.4 on 2021-02-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ships', '0004_auto_20210218_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalship',
            name='length',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
