# Generated by Django 2.2.4 on 2021-02-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ships', '0005_normalship_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalship',
            name='length',
        ),
        migrations.RemoveField(
            model_name='normalship',
            name='width',
        ),
        migrations.AddField(
            model_name='normalship',
            name='size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
