# Generated by Django 2.2.4 on 2021-02-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ships', '0007_auto_20210218_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wasteship',
            old_name='point',
            new_name='info',
        ),
    ]
